### ISSUE TITLE
Standardizing a Test Suite For External Use

### ISSUE THREAD

**Issue by b5** [qri-io/walk#4]
While building our [jsonschema package](https://github.com/qri-io/jsonschema), we had a _delightful_ experience working with their standardized test suite:
https://github.com/json-schema-org/JSON-Schema-Test-Suite

Included in this repo were a set of language-agnostic JSON files that defined both tests and expected outcomes. We copy-paste these into our repo, and ran the JSON as tests against our package to confirm we're matching the spec. The net result here is _we're reusing other people's tests_. That means _we're testing the same thing_, which ups chances things will work across language barriers.

Over time we've come to do very similar things at at qri that comes closer to this use case with our [dstest package](https://godoc.org/github.com/qri-io/dataset/dstest). For us doing everything as JSON files wasn't going to cut it, so we started to rely on directory structures & naming conventions as a way of structuring tests.

So with that I'm hoping to get a PR that focuses on the `lib/testdata` directory. It should include:
* a directory structure for listing test cases, where each folder is the name of the thing that's being checked. In each folder I'd like to see:
  * a folder for static test files that should be turned into a local server for testing
  * a naming convention for loading a walk configuration file: `config.json`
  * a folder: `resources` of expected generated resources, stored as JSON and/or CBOR files.
  * go code that assembles these cases with convenience methods for executing tests
  * code that skips / normalizes thing that vary, like timestamps
  * a result differ that shows differences between stored (expected) resource files & test results in a human-debugabble way

The goal here is outside software should be able to use these tests as well to confirm things are working as expected. The first test of weather this is effective or not should be getting @Mr0grog's puppeteer work to run these tests in js land.

**Comment by Mr0grog** [comment]
Note: one thing we’ll need to be able to test is that walk stays within its configured domains/hosts/origins, which means at least one test has to be able to spin up *two* web servers (that link to each other). We probably only need one test that does that, so it’s ok if the code for that one is a little fugly, but it does need to be possible.

**Comment by Mr0grog** [comment]
What’s the relationship between this and #3? Does this need to be done for #3 to function, but someone can do #3 at any time, regardless?

**Comment by b5** [comment]
yeah that's my expectation, I'd like to leave #3 unblocked so anyone is free to add in code according to the issue. If someone lands that test first, I'll modify the test to fit this format.
